import type { TranslationKeys } from './lang_es';

export const lang_en: TranslationKeys = {
  systemSettings: {
    sectionTitle: 'System Configuration',
    readOnlyModeLabel: 'Enable Read-Only Mode (Entire System)',
    readOnlyModeDesc: 'When enabled, ALL users will be unable to create episodes or notes when the central system is online',
    newEpisodeButtonLabel: 'Enable "New Episode" button',
    newEpisodeButtonDesc: 'When enabled, the button to create new episodes will be visible to all users',
  },

  readOnlyMode: {
    title: 'Read-Only Mode Active',
    loginAlert: '⚠️ Read-Only Mode Activated\n\nThe system detected a connection to the central server.\n\nDuring this time, you will not be able to:\n• Create new episodes\n• Record clinical notes\n\nYou will only be able to view existing information.',
    episodesBanner: 'The system detected a connection to the central server. During this time, you will only be able to view information. Episode and clinical note creation is disabled.',
    notesBanner: 'The system detected a connection to the central server. You cannot create new clinical notes at this time.',
    buttonTooltip: 'Not available in read-only mode',
    textareaPlaceholder: 'Not available in read-only mode',
  },

  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
  },

  header: {
    logout: 'Logout',
    settings: 'Settings',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    language: 'Language',
  },

  login: {
    title: 'Login',
    username: 'Username',
    password: 'Password',
    loginButton: 'Login',
    loginError: 'Invalid username or password',
  },

  episodes: {
    title: 'Episodes List',
    newEpisode: 'New Episode',
    viewNote: 'View Note',
    patient: 'Patient',
    mrn: 'MRN',
    run: 'ID',
    episode: 'Episode',
    type: 'Type',
    date: 'Date',
    dateAttention: 'Service Date',
    status: 'Status',
    hospital: 'Hospital',
    location: 'Location',
    professional: 'Professional',
    sync: 'Sync',
    noEpisodes: 'No episodes available',
    noEpisodesInCategory: 'No episodes in this category',
    loadingEpisodes: 'Loading episodes...',
    connected: 'Connected',
    disconnected: 'Disconnected',
    dataReception: 'Data reception (GET)',
    hl7Send: 'HL7 send (POST)',
    never: 'Never',
    pendingEvents: 'event',
    pendingEventsPlural: 'events',
    pending: 'pending',
    pendingPlural: 'pending',
    syncStatus: {
      online: 'Online',
      offline: 'Offline',
      pending: 'Pending sync',
      syncing: 'Syncing...',
      synced: 'Synced',
      pendingCount: 'Pending',
      new: 'New',
    },
  },

  clinicalNote: {
    title: 'Clinical Note',
    patientInfo: 'Patient Information',
    backToList: 'Back to list',
    backToEpisodes: 'Back to Episodes',
    saveNote: 'Save Note',
    saving: 'Saving...',
    clinicalRecord: 'Clinical Record',
    patient: 'Patient',
    sex: 'Sex',
    unknown: 'Unknown',
    birthDate: 'Date of Birth',
    attentionDate: 'Service Date',
    episodeType: 'Episode Type',
    professional: 'Professional',
    consultReason: 'Reason for Consultation',
    location: 'Location',
    room: 'Room',
    bed: 'Bed',
    previousNotes: 'Previous Clinical Notes',
    newNote: 'New Clinical Note',
    notePlaceholder: 'Write the clinical note here...',
    characters: 'characters',
    sent: 'Sent',
    pending: 'Pending',
    episodeNotFound: 'Episode not found',
    tabs: {
      subjective: 'Subjective',
      objective: 'Objective',
      assessment: 'Assessment',
      plan: 'Plan',
    },
    placeholders: {
      subjective: 'Chief complaint, symptoms reported by the patient...',
      objective: 'Vital signs, physical examination...',
      assessment: 'Diagnostic impression...',
      plan: 'Treatment, indications...',
    },
    saveSuccess: 'Clinical note saved successfully',
    saveError: 'Error saving note',
    loadError: 'Error loading episode data',
  },

  patientHistory: {
    title: 'Patient History',
    allergies: 'Allergies',
    offlineRecords: 'Offline Records',
    previousEncounters: 'Previous Encounters',
    labResults: 'Lab Results',
    noAllergies: 'No allergies recorded',
    noRecords: 'No offline records',
    noEncounters: 'No previous encounters recorded',
    noResults: 'No exam results',
    allergyTypes: {
      Medicamento: 'Medication',
      Alimento: 'Food',
      Ambiental: 'Environmental',
      Contacto: 'Contact',
    },
    severity: {
      Alta: 'High',
      Moderada: 'Moderate',
      Leve: 'Mild',
      Severa: 'Severe',
      Media: 'Medium',
      Baja: 'Low',
    },
    active: 'Active',
    inactive: 'Inactive',
    viewFullNote: 'Click to view full',
    noteDetails: 'Offline Record Details',
    dateTime: 'Date and Time',
    responsible: 'Responsible',
    note: 'Note',
    fullNote: 'Full Note',
    close: 'Close',
    consultReason: 'Reason for Consultation',
    diagnoses: 'Diagnoses',
    medications: 'Medications',
    indications: 'Indications',
    examType: 'Type',
    exam: 'Exam',
    exams: 'exams',
    value: 'Value',
    referenceRange: 'Reference range',
    doctor: 'Doctor',
    specialty: 'Specialty',
    type: 'Type',
    abnormalFlag: {
      Normal: 'Normal',
      Alto: 'High',
      Bajo: 'Low',
      High: 'High',
      Low: 'Low',
    },
  },

  newEpisode: {
    title: 'New Episode',
    titlePatient: 'New Patient + Episode',
    backToEpisodes: 'Back to Episodes',
    searchPatient: 'Search Patient',
    searchPlaceholder: 'Search by name, ID or MRN',
    selectPatient: 'Select patient to create episode',
    patientInfo: 'Patient Information',
    patientData: 'Patient Data',
    episodeInfo: 'Episode Information',
    episodeData: 'Episode Data',
    createEpisode: 'Create Episode',
    createAndContinue: 'Create and Continue',
    creating: 'Creating...',
    cancel: 'Cancel',
    episodeNumber: 'Episode Number',
    type: 'Type',
    episodeType: 'Episode Type',
    noEpisodeTypes: 'No types available',
    date: 'Date of Service',
    hospital: 'Hospital',
    room: 'Room',
    roomBox: 'Room/Box',
    bed: 'Bed',
    location: 'Location',
    local: 'Local',
    clinicUnit: 'Clinical Unit',
    clinicUnitPlaceholder: 'Select location...',
    clinicUnitNoData: 'No locations available for this episode type',
    clinicUnitNoDataSync: 'No locations available. Sync data from central system.',
    clinicUnitNoResults: 'No locations found',
    status: 'Status',
    professional: 'Professional',
    firstName: 'First Name',
    lastName: 'Last Name',
    rut: 'ID',
    noDocument: 'No Document',
    sex: 'Sex',
    birthDate: 'Date of Birth',
    consultReason: 'Reason for Consultation',
    required: 'This field is required',
    createSuccess: 'Episode created successfully',
    createError: 'Error creating episode',
    sexOptions: {
      M: 'Male',
      F: 'Female',
      O: 'Other',
      U: 'Unknown',
    },
  },

  timeAgo: {
    justNow: 'Just now',
    secondsAgo: '{count} second ago',
    secondsAgoPlural: '{count} seconds ago',
    minutesAgo: '{count} minute ago',
    minutesAgoPlural: '{count} minutes ago',
    hoursAgo: '{count} hour ago',
    hoursAgoPlural: '{count} hours ago',
    daysAgo: '{count} day ago',
    daysAgoPlural: '{count} days ago',
    weeksAgo: '{count} week ago',
    weeksAgoPlural: '{count} weeks ago',
    monthsAgo: '{count} month ago',
    monthsAgoPlural: '{count} months ago',
    yearsAgo: '{count} year ago',
    yearsAgoPlural: '{count} years ago',
  },

  userSettings: {
    title: 'User Settings',
    filters: 'Filters',
    hospitals: 'Hospitals',
    locations: 'Locations',
    professionals: 'Professionals',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    saveSuccess: 'Settings saved successfully',
    saveError: 'Error saving settings',
  },

  episodeTypes: {
    'Urgencia': 'Emergency',
    'Ambulatorio': 'Outpatient',
    'Hospitalizado': 'Inpatient',
    'Emergencia': 'Emergency',
  },

  episodeStatus: {
    'Activo': 'Active',
    'En Atención': 'In Care',
    'Finalizado': 'Completed',
    'Pendiente': 'Pending',
  },
};
