export const lang_es = {
  systemSettings: {
    sectionTitle: 'Configuración del Sistema',
    readOnlyModeLabel: 'Habilitar Modo Solo Lectura (Todo el Sistema)',
    readOnlyModeDesc: 'Cuando está habilitado, TODOS los usuarios no podrán crear episodios ni notas cuando el sistema central esté en línea',
    newEpisodeButtonLabel: 'Habilitar botón "Nuevo Episodio"',
    newEpisodeButtonDesc: 'Cuando está habilitado, el botón para crear nuevos episodios será visible para todos los usuarios',
  },

  readOnlyMode: {
    title: 'Modo Solo Lectura Activo',
    loginAlert: '⚠️ Modo Solo Lectura Activado\n\nEl sistema detectó conexión con el servidor central.\n\nDurante este tiempo, no podrá:\n• Crear nuevos episodios\n• Registrar notas clínicas\n\nSolo podrá consultar información existente.',
    episodesBanner: 'El sistema detectó conexión con el servidor central. Durante este tiempo, solo podrá consultar información. La creación de episodios y notas clínicas está deshabilitada.',
    notesBanner: 'El sistema detectó conexión con el servidor central. No podrá crear nuevas notas clínicas en este momento.',
    buttonTooltip: 'No disponible en modo solo lectura',
    textareaPlaceholder: 'No disponible en modo solo lectura',
  },
  common: {
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    search: 'Buscar',
    close: 'Cerrar',
    yes: 'Sí',
    no: 'No',
  },

  header: {
    logout: 'Cerrar sesión',
    settings: 'Configuración',
    darkMode: 'Modo oscuro',
    lightMode: 'Modo claro',
    language: 'Idioma',
  },

  login: {
    title: 'Iniciar sesión',
    username: 'Usuario',
    password: 'Contraseña',
    loginButton: 'Ingresar',
    loginError: 'Usuario o contraseña incorrectos',
  },

  episodes: {
    title: 'Lista de Episodios',
    newEpisode: 'Nuevo Episodio',
    viewNote: 'Ver Nota',
    patient: 'Paciente',
    mrn: 'MRN',
    run: 'RUN',
    episode: 'Episodio',
    type: 'Tipo',
    date: 'Fecha',
    dateAttention: 'Fecha Atención',
    status: 'Estado',
    hospital: 'Hospital',
    location: 'Ubicación',
    professional: 'Profesional',
    sync: 'Sincronización',
    noEpisodes: 'No hay episodios disponibles',
    noEpisodesInCategory: 'No hay episodios en esta categoría',
    loadingEpisodes: 'Cargando episodios...',
    connected: 'Conectado',
    disconnected: 'Sin conexión',
    dataReception: 'Recepción datos (GET)',
    hl7Send: 'Envío HL7 (POST)',
    never: 'Nunca',
    pendingEvents: 'evento',
    pendingEventsPlural: 'eventos',
    pending: 'pendiente',
    pendingPlural: 'pendientes',
    syncStatus: {
      online: 'Conectado',
      offline: 'Sin conexión',
      pending: 'Pendiente de sincronización',
      syncing: 'Sincronizando...',
      synced: 'Sincronizado',
      pendingCount: 'Pendiente',
      new: 'Nuevo',
    },
  },

  clinicalNote: {
    title: 'Nota Clínica',
    patientInfo: 'Información del Paciente',
    backToList: 'Volver a lista',
    backToEpisodes: 'Volver a Episodios',
    saveNote: 'Guardar Nota',
    saving: 'Guardando...',
    clinicalRecord: 'Registro Clínico',
    patient: 'Paciente',
    sex: 'Sexo',
    unknown: 'Desconocido',
    birthDate: 'Fecha de Nacimiento',
    attentionDate: 'Fecha de Atención',
    episodeType: 'Tipo de Episodio',
    professional: 'Profesional',
    consultReason: 'Motivo de Consulta',
    location: 'Ubicación',
    room: 'Habitación',
    bed: 'Cama',
    previousNotes: 'Notas Clínicas Anteriores',
    newNote: 'Nueva Nota Clínica',
    notePlaceholder: 'Escriba aquí la nota clínica...',
    characters: 'caracteres',
    sent: 'Enviado',
    pending: 'Pendiente',
    episodeNotFound: 'Episodio no encontrado',
    tabs: {
      subjective: 'Subjetivo',
      objective: 'Objetivo',
      assessment: 'Evaluación',
      plan: 'Plan',
    },
    placeholders: {
      subjective: 'Motivo de consulta, síntomas referidos por el paciente...',
      objective: 'Signos vitales, examen físico...',
      assessment: 'Impresión diagnóstica...',
      plan: 'Tratamiento, indicaciones...',
    },
    saveSuccess: 'Nota clínica guardada exitosamente',
    saveError: 'Error al guardar la nota',
    loadError: 'Error al cargar los datos del episodio',
  },

  patientHistory: {
    title: 'Antecedentes del Paciente',
    allergies: 'Alergias',
    offlineRecords: 'Registros Offline',
    previousEncounters: 'Encuentros Previos',
    labResults: 'Resultados de Exámenes',
    noAllergies: 'No hay alergias registradas',
    noRecords: 'No hay registros offline',
    noEncounters: 'No hay encuentros previos registrados',
    noResults: 'No hay resultados de exámenes',
    allergyTypes: {
      Medicamento: 'Medicamento',
      Alimento: 'Alimento',
      Ambiental: 'Ambiental',
      Contacto: 'Contacto',
    },
    severity: {
      Alta: 'Alta',
      Moderada: 'Moderada',
      Leve: 'Leve',
      Severa: 'Severa',
      Media: 'Media',
      Baja: 'Baja',
    },
    active: 'Activa',
    inactive: 'Inactiva',
    viewFullNote: 'Click para ver completo',
    noteDetails: 'Detalle de Registro Offline',
    dateTime: 'Fecha y Hora',
    responsible: 'Responsable',
    note: 'Nota',
    fullNote: 'Nota Completa',
    close: 'Cerrar',
    consultReason: 'Motivo de Consulta',
    diagnoses: 'Diagnósticos',
    medications: 'Medicamentos',
    indications: 'Indicaciones',
    examType: 'Tipo',
    exam: 'Examen',
    exams: 'exámenes',
    value: 'Valor',
    referenceRange: 'Rango de referencia',
    doctor: 'Médico',
    specialty: 'Especialidad',
    type: 'Tipo',
    abnormalFlag: {
      Normal: 'Normal',
      Alto: 'Alto',
      Bajo: 'Bajo',
      High: 'Alto',
      Low: 'Bajo',
    },
  },

  newEpisode: {
    title: 'Nuevo Episodio',
    titlePatient: 'Nuevo Paciente + Episodio',
    backToEpisodes: 'Volver a Episodios',
    searchPatient: 'Buscar Paciente',
    searchPlaceholder: 'Buscar por nombre, RUN o MRN',
    selectPatient: 'Seleccionar paciente para crear episodio',
    patientInfo: 'Información del Paciente',
    patientData: 'Datos del Paciente',
    episodeInfo: 'Información del Episodio',
    episodeData: 'Datos del Episodio',
    createEpisode: 'Crear Episodio',
    createAndContinue: 'Crear y Continuar',
    creating: 'Creando...',
    cancel: 'Cancelar',
    episodeNumber: 'Número de Episodio',
    type: 'Tipo',
    episodeType: 'Tipo de Episodio',
    noEpisodeTypes: 'No hay tipos disponibles',
    date: 'Fecha de Atención',
    hospital: 'Hospital',
    room: 'Habitación',
    roomBox: 'Habitación/Box',
    bed: 'Cama',
    location: 'Ubicación',
    local: 'Local',
    clinicUnit: 'Unidad Clínica',
    clinicUnitPlaceholder: 'Seleccionar ubicación...',
    clinicUnitNoData: 'No hay ubicaciones disponibles para este tipo de episodio',
    clinicUnitNoDataSync: 'No hay ubicaciones disponibles. Sincronice datos del sistema central.',
    clinicUnitNoResults: 'No se encontraron ubicaciones',
    status: 'Estado',
    professional: 'Profesional',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    rut: 'RUT',
    noDocument: 'Sin Documento',
    sex: 'Sexo',
    birthDate: 'Fecha de Nacimiento',
    consultReason: 'Motivo de Consulta',
    required: 'Este campo es requerido',
    createSuccess: 'Episodio creado exitosamente',
    createError: 'Error al crear el episodio',
    sexOptions: {
      M: 'Masculino',
      F: 'Femenino',
      O: 'Otro',
      U: 'Desconocido',
    },
  },

  timeAgo: {
    justNow: 'Justo ahora',
    secondsAgo: 'hace {count} segundo',
    secondsAgoPlural: 'hace {count} segundos',
    minutesAgo: 'hace {count} minuto',
    minutesAgoPlural: 'hace {count} minutos',
    hoursAgo: 'hace {count} hora',
    hoursAgoPlural: 'hace {count} horas',
    daysAgo: 'hace {count} día',
    daysAgoPlural: 'hace {count} días',
    weeksAgo: 'hace {count} semana',
    weeksAgoPlural: 'hace {count} semanas',
    monthsAgo: 'hace {count} mes',
    monthsAgoPlural: 'hace {count} meses',
    yearsAgo: 'hace {count} año',
    yearsAgoPlural: 'hace {count} años',
  },

  userSettings: {
    title: 'Configuración de Usuario',
    filters: 'Filtros',
    hospitals: 'Hospitales',
    locations: 'Ubicaciones',
    professionals: 'Profesionales',
    selectAll: 'Seleccionar todos',
    deselectAll: 'Deseleccionar todos',
    saveSuccess: 'Configuración guardada exitosamente',
    saveError: 'Error al guardar la configuración',
  },

  episodeTypes: {
    'Urgencia': 'Urgencia',
    'Ambulatorio': 'Ambulatorio',
    'Hospitalizado': 'Hospitalizado',
    'Emergencia': 'Emergencia',
  },

  episodeStatus: {
    'Activo': 'Activo',
    'En Atención': 'En Atención',
    'Finalizado': 'Finalizado',
    'Pendiente': 'Pendiente',
  },
};

export type TranslationKeys = typeof lang_es;
